<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="0" tests="9" time="0.329" timestamp="2022-01-31T12:04:46.648988" hostname="DESKTOP-GHP0TU5"><testcase classname="test_first" name="test_1" time="0.001" /><testcase classname="test_first" name="test_2" time="0.002" /><testcase classname="test_first" name="test_3" time="0.002"><failure message="AssertionError: Title does not match&#10;assert 'jenkins' is 'Jenkins is CI server'">def test_3():
        name = "jenkins"
        title = "Jenkins is CI server"
&gt;       assert name is title , "Title does not match"
E       AssertionError: Title does not match
E       assert 'jenkins' is 'Jenkins is CI server'

test_first.py:17: AssertionError</failure></testcase><testcase classname="test_four" name="test_responsecode200" time="0.002" /><testcase classname="test_four" name="test_responsecode400" time="0.001" /><testcase classname="test_second" name="test_login" time="0.002" /><testcase classname="test_second" name="test_checkout" time="0.001" /><testcase classname="test_second" name="test_logout" time="0.001" /><testcase classname="test_three.MyTestCase" name="test_something" time="0.003"><failure message="AssertionError: True != False">self = &lt;test_three.MyTestCase testMethod=test_something&gt;

    def test_something(self):
&gt;       self.assertEqual(True , False)
E       AssertionError: True != False

test_three.py:5: AssertionError</failure></testcase></testsuite></testsuites>